from fastapi import Depends, FastAPI
from sqlalchemy import select
from sqlalchemy.orm import Session

from .database import Base, engine, get_db
from .models import SensorReading
from .schemas import SensorReadingCreate, SensorReadingResponse


#creates any missing tables when the API starts up
Base.metadata.create_all(bind=engine)


#creates the FastAPI application
app = FastAPI(
    title="Cownect Backend API",
    version="0.1.0",
)


#message used to check if API is healthy
@app.get("/health")
def health():
    return {"status": "healthy"}


#receives a JSON from the Jetson and saves it to the database
@app.post(
    "/api/v1/readings",
    response_model=SensorReadingResponse,
    status_code=201,
)
def create_reading(
    reading: SensorReadingCreate,
    db: Session = Depends(get_db),
):
    #converts the reading into a row in the database
    database_reading = SensorReading(**reading.model_dump())

    #adds the row to the database session
    db.add(database_reading)

    #saves row in PostgreSQL
    db.commit()

    #refreshes row to get any values generated by PostgreSQL like row #
    db.refresh(database_reading)

    #returns row saved
    return database_reading


#returns the 100 latest readings
@app.get(
    "/api/v1/readings",
    response_model=list[SensorReadingResponse],
)
def get_readings(db: Session = Depends(get_db)):
    #places newest readings first
    query = (
        select(SensorReading)
        .order_by(SensorReading.recorded_at.desc())
        .limit(100)
    )

    #runs query and returns the results as a list of SensorReading objects
    return db.scalars(query).all()